stages:
  - build
  - test
  - docker
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build_job:
  stage: build
  image: gradle:7.6.1-jdk17
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

test_job:
  stage: test
  image: gradle:7.6.1-jdk17
  script:
    - ./gradlew test
  dependencies:
    - build_job

docker_build_job:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  dependencies:
    - build_job

deploy_job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 192.168.0.222 >> ~/.ssh/known_hosts
  script:
    - ssh seyed@192.168.0.222 "
        docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD &&
        docker pull $IMAGE_NAME &&
        docker stop myapp || true &&
        docker rm myapp || true &&
        docker run -d --name myapp -p 8080:8080 $IMAGE_NAME"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'